# Generated by Django 6.0 on 2025-12-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_passowrd', models.CharField(max_length=255)),
                ('new_passowrd', models.CharField(max_length=255)),
                ('confirm_new_passowrd', models.CharField(max_length=255)),
            ],
        ),
    ]
