# Generated by Django 6.0 on 2025-12-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_password', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='confirm_new_passowrd',
            new_name='confirm_new_password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='new_passowrd',
            new_name='new_password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='old_passowrd',
            new_name='old_password',
        ),
    ]
