# Generated by Django 6.0 on 2025-12-24 11:05

import find_password.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_password', '0002_rename_confirm_new_passowrd_account_confirm_new_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='confirm_new_password',
            field=models.CharField(max_length=255, validators=[find_password.validators.check_length]),
        ),
        migrations.AlterField(
            model_name='account',
            name='new_password',
            field=models.CharField(max_length=255, validators=[find_password.validators.check_length]),
        ),
        migrations.AlterField(
            model_name='account',
            name='old_password',
            field=models.CharField(max_length=255, validators=[find_password.validators.check_length]),
        ),
    ]
