# Generated by Django 6.0 on 2025-12-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_password', '0003_alter_account_confirm_new_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='confirm_new_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='new_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='old_password',
            field=models.CharField(max_length=255),
        ),
    ]
